version: '3.1'

services:
  zoo1:
    image: zookeeper
    container_name: zoo1
    restart: unless-stopped
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181

  zoo2:
    image: zookeeper
    container_name: zoo2
    restart: unless-stopped
    hostname: zoo2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zoo3:2888:3888;2181

  zoo3:
    image: zookeeper
    container_name: zoo3
    restart: unless-stopped
    hostname: zoo3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181

  kafka1:
    image: wurstmeister/kafka
    container_name: kafka1
    restart: unless-stopped
    depends_on: [ zoo1, zoo2, zoo3 ]
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${hostIp}
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2  # if only one broker set it 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${hostIp}:9092
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181

  kafka2:
    image: wurstmeister/kafka
    container_name: kafka2
    restart: unless-stopped
    depends_on: [ zoo1, zoo2, zoo3 ]
    ports:
      - 9093:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${hostIp}
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_BROKER_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${hostIp}:9093
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181

  kafka3:
    image: wurstmeister/kafka
    container_name: kafka3
    restart: unless-stopped
    depends_on: [ zoo1, zoo2, zoo3 ]
    ports:
      - 9094:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${hostIp}
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_BROKER_ID: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${hostIp}:9094
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181

  kafka-manager:
    image: sheepkiller/kafka-manager 
    container_name: kafka-manager
    restart: unless-stopped   
    depends_on: [ kafka1, kafka2, kafka3 ]
    environment:
        ZK_HOSTS: zoo1:2181,zoo2:2181,zoo3:2181                
    ports:
      - 9000:9000   