version: '3.1'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    hostname: elasticsearch
    ports: 
      - 9200:9200
    environment:
      - discovery.type=single-node
    
  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.4
    depends_on: [ elasticsearch ]
    ports:
      - 5601:5601
    environment: 
      - ELASTICSEARCH_URL=http://elasticsearch:9200
